# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #General configuration
  config.ssh.username = 'admin'
  config.ssh.private_key_path = './acit_4640_base/acit_admin_id_rsa'

  #Specifiy the base box here
  config.vm.box = 'centos_base'

  #VM specific configuration
  #see : https://www.vagrantup.com/docs/multi-machine/
  config.vm.define "wp_vagrant" do |wp_vagrant|
    wp_vagrant.vm.hostname = "wp.host.name"
    wp_vagrant.vm.network "forwarded_port", guest: 443, host: 50443
    wp_vagrant.vm.network "forwarded_port", guest: 80, host: 50080
    #other machine configuration items go here
    wp_vagrant.vm.provider "virtualbox" do |vb|
      vb.name = "wp_server_vagrant"
      vb.linked_clone = true
      vb.gui = true

      #all other provider configuration items go here
    end
  end

  config.vm.provision "file", source: "./wp_setup.sh", destination: "/home/admin/wp_setup.sh"
  config.vm.provision "file", source: "./config", destination: "/home/admin/config"

  #General provisioning Configuration 
  config.vm.provision "shell", inline: "/home/admin/wp_setup.sh"
end