---
# handlers file for mariadb

- name: disallow remote mariadb root login
  command: 'mysql --user=root -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: false

- name: set mariadb root password
  mysql_user: 
    login_user: root
    name: root
    password: "{{ mariadb_priv_user_passwd }}"

- name: remove anonymous mariadb users
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mariadb_priv_user_passwd }}"

- name: remove mariadb test db
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mariadb_priv_user_passwd }}"

- name: restart mariadb
  service: 
    name: mariadb
    state: restarted
  become: true

...
