---
- name: Install Rsync
  yum: name=rsync state=present

- name: create wordpress db
  mysql_db:
    login_user: "{{ mariadb_priv_user }}"
    login_password: "{{ mariadb_priv_user_passwd }}"
    name: "{{ wordpress_db }}"

- name: create wordpress db user
  mysql_user:
    login_user: "{{ mariadb_priv_user }}"
    login_password: "{{ mariadb_priv_user_passwd }}"
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_user_passwd }}"
    priv: "{{ wordpress_db }}.*:ALL"
    state: present

- name: Download Wordpress
  get_url: 
    url: http://wordpress.org/latest.tar.gz 
    dest: /home/centos/wordpress.tar.gz

- name: Unpack Wordpress Archive
  unarchive: 
    remote_src: yes 
    src: /home/centos/wordpress.tar.gz 
    dest: /home/centos

- name: Copy Wordpress to nginx folder
  command: rsync -avP /home/centos/wordpress/ /usr/share/nginx/html/

- name: Create Wordpress uploads folder
  file: 
    path: /usr/share/nginx/html/wp-content/uploads 
    state: directory

- name: Copy Wordpress Configuration
  copy:
    src: wp-config.php
    dest: /usr/share/nginx/html/

- name: Set Wordpress Permission
  file:
    path: /usr/share/nginx/html/
    mode: 0755
    owner: centos
    group: nginx
    state: directory
    recurse: yes