galaxy_info:
  author: Thomas Lane
  description: installs and secures MariaDB 

  license: BSD

  min_ansible_version: 2.1

  platforms:
  - name: EL
    versions:
      - 7
    galaxy_tags: 
     - centos
     - mysql
     - mariadb

dependencies: []
