#cloud-config user-data
# see http://cloudinit.readthedocs.io/en/latest/topics/modules.html
repo_update: true
repo_upgrade: all

packages:
  #Ensure python is available for ansible
  - python

runcmd:
  #Allows permitted users to run sudo without a teminal - required by ansible
  - sed -i 's/^\(Defaults\s\+requiretty\)/#\1/' /etc/sudoers
  #Turn off selinux - temporarily make our lives easier
  - setenforce 0
  - sed -r -i 's/SELINUX=(enforcing|disabled)/SELINUX=permissive/' /etc/selinux/config
